import { AmenityItem } from "../types";

export const MOCK_AMENITIES: AmenityItem[] = [
  // 1. Thiết yếu (ESSENTIAL)
  {
    id: "amenity-wifi",
    nameVi: "Wi-Fi tốc độ cao",
    nameEn: "High-speed Wi-Fi",
    category: "ESSENTIAL",
    iconName: "Wifi",
    descriptionVi: "Kết nối ổn định 100Mbps, phù hợp làm việc từ xa",
    descriptionEn: "Stable 100Mbps connection, remote-work friendly",
  },
  {
    id: "amenity-aircon",
    nameVi: "Điều hoà không khí",
    nameEn: "Air conditioning",
    category: "ESSENTIAL",
    iconName: "AirVent",
    descriptionVi: "Điều hòa hai chiều làm mát và sưởi",
    descriptionEn: "Inverter cooling and heating",
  },
  {
    id: "amenity-hotwater",
    nameVi: "Máy nước nóng",
    nameEn: "Hot water",
    category: "ESSENTIAL",
    iconName: "Droplets",
    descriptionVi: "Nước nóng liên tục trong nhà tắm",
    descriptionEn: "Continuous hot water supply",
  },
  {
    id: "amenity-workdesk",
    nameVi: "Bàn làm việc riêng",
    nameEn: "Dedicated workspace",
    category: "ESSENTIAL",
    iconName: "Laptop",
    descriptionVi: "Bàn ghế công thái học kèm ổ cắm điện",
    descriptionEn: "Ergonomic chair and desk with power outlets",
  },
  {
    id: "amenity-iron",
    nameVi: "Bàn ủi / Máy là hơi nước",
    nameEn: "Iron / Garment steamer",
    category: "ESSENTIAL",
    iconName: "Shirt",
    descriptionVi: "Có sẵn bàn để ủi đồ",
    descriptionEn: "Iron and ironing board available",
  },
  {
    id: "amenity-hairdryer",
    nameVi: "Máy sấy tóc",
    nameEn: "Hair dryer",
    category: "ESSENTIAL",
    iconName: "Wind",
    descriptionVi: "Công suất lớn trong mỗi phòng tắm",
    descriptionEn: "High power hair dryer in each bathroom",
  },
  {
    id: "amenity-linens",
    nameVi: "Khăn tắm & Ga trải giường",
    nameEn: "Towels & Bed linens",
    category: "ESSENTIAL",
    iconName: "Sparkles",
    descriptionVi: "Được thay mới sạch sẽ trước mỗi lượt khách",
    descriptionEn: "Fresh and clean linens provided per stay",
  },

  // 2. Phòng bếp (KITCHEN)
  {
    id: "amenity-stove",
    nameVi: "Bếp nấu (Từ / Ga)",
    nameEn: "Kitchen stove (Induction / Gas)",
    category: "KITCHEN",
    iconName: "ChefHat",
    descriptionVi: "Đầy đủ nồi chảo cho khách tự nấu ăn",
    descriptionEn: "Cookware and pans provided for self-cooking",
  },
  {
    id: "amenity-fridge",
    nameVi: "Tủ lạnh",
    nameEn: "Refrigerator",
    category: "KITCHEN",
    iconName: "Refrigerator",
    descriptionVi: "Tủ lạnh có ngăn đông bảo quản thực phẩm",
    descriptionEn: "Spacious fridge with freezer compartment",
  },
  {
    id: "amenity-microwave",
    nameVi: "Lò vi sóng",
    nameEn: "Microwave",
    category: "KITCHEN",
    iconName: "Microwave",
    descriptionVi: "Hâm nóng thức ăn nhanh chóng",
    descriptionEn: "Convenient for quick meal reheating",
  },
  {
    id: "amenity-coffeemaker",
    nameVi: "Máy pha cà phê / Ấm siêu tốc",
    nameEn: "Coffee maker / Electric kettle",
    category: "KITCHEN",
    iconName: "Coffee",
    descriptionVi: "Kèm trà và cà phê túi lọc miễn phí",
    descriptionEn: "Complimentary tea and drip coffee provided",
  },
  {
    id: "amenity-dishes",
    nameVi: "Bát đĩa & Đồ dùng ăn uống",
    nameEn: "Dishes & Silverware",
    category: "KITCHEN",
    iconName: "UtensilsCrossed",
    descriptionVi: "Đủ bộ cho số lượng khách tối đa",
    descriptionEn: "Complete sets tailored for max guests",
  },

  // 3. Tiện nghi phòng tắm (BATHROOM)
  {
    id: "amenity-bathtub",
    nameVi: "Bồn tắm nằm",
    nameEn: "Bathtub",
    category: "BATHROOM",
    iconName: "Bath",
    descriptionVi: "Bồn ngâm thư giãn",
    descriptionEn: "Soaking bathtub for relaxation",
  },
  {
    id: "amenity-toiletries",
    nameVi: "Dầu gội & Sữa tắm cao cấp",
    nameEn: "Shampoo & Body soap",
    category: "BATHROOM",
    iconName: "Sparkles",
    descriptionVi: "Sản phẩm hữu cơ lành tính",
    descriptionEn: "Organic and skin-friendly toiletries",
  },
  {
    id: "amenity-washingmachine",
    nameVi: "Máy giặt riêng",
    nameEn: "Washing machine",
    category: "BATHROOM",
    iconName: "Wind",
    descriptionVi: "Có kèm nước giặt miễn phí",
    descriptionEn: "In-unit laundry with free detergent",
  },

  // 4. Giải trí (ENTERTAINMENT)
  {
    id: "amenity-smarttv",
    nameVi: "Smart TV (Netflix / YouTube)",
    nameEn: "Smart TV (Netflix / YouTube)",
    category: "ENTERTAINMENT",
    iconName: "Tv",
    descriptionVi: "Màn hình 55 inch độ phân giải 4K",
    descriptionEn: "55-inch 4K screen with streaming apps",
  },
  {
    id: "amenity-speaker",
    nameVi: "Loa Bluetooth",
    nameEn: "Bluetooth sound speaker",
    category: "ENTERTAINMENT",
    iconName: "Speaker",
    descriptionVi: "Âm thanh vòm chất lượng cao",
    descriptionEn: "High fidelity wireless sound system",
  },
  {
    id: "amenity-boardgames",
    nameVi: "Board games & Sách",
    nameEn: "Board games & Books",
    category: "ENTERTAINMENT",
    iconName: "BookOpen",
    descriptionVi: "Nhiều trò chơi giải trí nhóm",
    descriptionEn: "Party games and reading books collection",
  },

  // 5. An toàn (SAFETY)
  {
    id: "amenity-fireext",
    nameVi: "Bình chữa cháy",
    nameEn: "Fire extinguisher",
    category: "SAFETY",
    iconName: "Flame",
    descriptionVi: "Bố trí tại cửa ra vào và bếp",
    descriptionEn: "Positioned at entrance and kitchen",
  },
  {
    id: "amenity-firstaid",
    nameVi: "Hộp sơ cứu y tế",
    nameEn: "First aid kit",
    category: "SAFETY",
    iconName: "ShieldAlert",
    descriptionVi: "Băng gạc, sát khuẩn, thuốc cơ bản",
    descriptionEn: "Bandages, antiseptics, and basic OTC aids",
  },
  {
    id: "amenity-smokemonitor",
    nameVi: "Thiết bị báo khói & khí CO",
    nameEn: "Smoke & CO alarm",
    category: "SAFETY",
    iconName: "BellRing",
    descriptionVi: "Cảm biến tiêu chuẩn an toàn",
    descriptionEn: "Certified indoor safety sensor",
  },
  {
    id: "amenity-smartlock",
    nameVi: "Khoá cửa thông minh / Tự nhận phòng",
    nameEn: "Smart lock / Self check-in",
    category: "SAFETY",
    iconName: "KeyRound",
    descriptionVi: "Nhập mã số để mở cửa 24/7",
    descriptionEn: "Keyless entry passcode 24/7",
  },

  // 6. Ngoài trời (OUTDOOR)
  {
    id: "amenity-balcony",
    nameVi: "Ban công / Sân hiên thoáng đãng",
    nameEn: "Balcony / Scenic patio",
    category: "OUTDOOR",
    iconName: "Sun",
    descriptionVi: "Góc ngắm cảnh thoáng mát",
    descriptionEn: "Open scenic view with outdoor seats",
  },
  {
    id: "amenity-bbq",
    nameVi: "Bếp nướng BBQ ngoài trời",
    nameEn: "Outdoor BBQ grill",
    category: "OUTDOOR",
    iconName: "Flame",
    descriptionVi: "Có vỉ nướng và than củi hỗ trợ",
    descriptionEn: "Grill equipment and charcoal available",
  },
  {
    id: "amenity-parking",
    nameVi: "Chỗ đỗ xe miễn phí",
    nameEn: "Free on-site parking",
    category: "OUTDOOR",
    iconName: "Car",
    descriptionVi: "Đỗ được ô tô 4-7 chỗ an toàn",
    descriptionEn: "Secure parking for cars and motorbikes",
  },
  {
    id: "amenity-pool",
    nameVi: "Bể bơi riêng / Bể bơi chung",
    nameEn: "Private / Shared swimming pool",
    category: "OUTDOOR",
    iconName: "Waves",
    descriptionVi: "Nước xử lý clo sạch chuẩn",
    descriptionEn: "Clean and filtered swimming pool",
  },
];

export async function getAvailableAmenities(): Promise<AmenityItem[]> {
  await new Promise((r) => setTimeout(r, 60));
  return JSON.parse(JSON.stringify(MOCK_AMENITIES));
}
