spring:
  application:
    name: homestay-backend
  profiles:
    active: local

app:
  name: "Homestay Booking Platform"
  environment: "default"
  security:
    session-cookie-name: "HOMESTAY_SESSION"
